# Generated by Selenium IDE
import time
from core.selenium.common import initialize_driver, close_driver
from selenium.webdriver.common.by import By


class TestRatefeaturemodel():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    close_driver(self.driver)
  
  def test_ratefeaturemodel(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1854, 1048)
    self.driver.find_element(By.LINK_TEXT, "View dataset").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Elephants").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active:nth-child(4)").click()
    time.sleep(0.5) # needed to wait for alert to appear
    assert self.driver.switch_to.alert.text == "Rating saved successfully"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".d-block").click()
    self.driver.find_element(By.LINK_TEXT, "Tigers").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2) .model-rating-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active:nth-child(3)").click()
    time.sleep(0.5)
    assert self.driver.switch_to.alert.text == "Rating saved successfully"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(4) .fa:nth-child(2)").click()
    time.sleep(0.5)
    assert self.driver.switch_to.alert.text == "Rating saved successfully"
    self.driver.switch_to.alert.accept()
