# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from core.selenium.common import initialize_driver, close_driver

class TestChatbotoutofcontext():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}

  def teardown_method(self, method):
    close_driver(self.driver)

  def test_chatbotoutofcontext(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1920, 1048)
    self.driver.find_element(By.LINK_TEXT, "Romeo").click()
    self.driver.find_element(By.ID, "chatInput").click()
    self.driver.find_element(By.ID, "chatInput").send_keys("Hola Romeo, hablame de las elecciones de EEUU")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "chatInput").click()
    self.driver.find_element(By.ID, "chatInput").send_keys("Cuantos cristianos hay en el mundo?")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "chatInput").click()