# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from core.selenium.common import initialize_driver, close_driver

class TestTestmaxminuvlfilterUI:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        close_driver(self.driver)

    def test_testmaxminuvlfilterUI(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1761, 962)
        sidebar_item = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)")))
        sidebar_item.click()
        min_uvl = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "min_uvl")))
        min_uvl.click()
        min_uvl.send_keys("1")
        self.driver.find_element(By.ID, "search-button").click()
        min_uvl.clear()
        min_uvl.send_keys("10")
        self.driver.find_element(By.ID, "search-button").click()
        min_uvl.clear()
        min_uvl.send_keys("3")
        self.driver.find_element(By.ID, "search-button").click()
        max_uvl = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "max_uvl")))
        max_uvl.click()
        max_uvl.send_keys("10")
        self.driver.find_element(By.ID, "search-button").click()
        filters_button = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "filters")))
        filters_button.click()