# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from core.selenium.common import initialize_driver, close_driver

class TestTestpublicationtypefilterUI:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        close_driver(self.driver)

    def test_testpublicationtypefilterUI(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1761, 962)
        sidebar_item = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)")))
        sidebar_item.click()
        publication_type = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "publication_type")))
        publication_type.click()
        option_dmp = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//option[. = 'Data Management Plan']")))
        option_dmp.click()
        self.driver.find_element(By.ID, "search-button").click()
        publication_type.click() 
        option_book = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//option[. = 'Book']")))
        option_book.click()
        self.driver.find_element(By.ID, "search-button").click()
        actions = ActionChains(self.driver)
        actions.move_to_element(publication_type).click_and_hold().perform()
        actions.move_to_element(publication_type).release().perform()