# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from core.selenium.common import initialize_driver, close_driver

class TestTestclearfiltersbuttonUI():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}

  def teardown_method(self, method):
    close_driver(self.driver)

  def test_testclearfiltersbuttonUI(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1920, 1048)
    self.driver.find_element(By.LINK_TEXT, "Explore").click()
    self.driver.find_element(By.ID, "publication_type").click()
    self.driver.find_element(By.ID, "end_date").click()
    self.driver.find_element(By.ID, "end_date").send_keys("2023-12-09")
    self.driver.find_element(By.ID, "min_size").click()
    self.driver.find_element(By.ID, "min_uvl").click()
    self.driver.find_element(By.ID, "min_uvl").send_keys("05")
    self.driver.find_element(By.ID, "search-button").click()
    self.driver.find_element(By.ID, "clear-filters").click()
    self.driver.find_element(By.ID, "search-button").click()
    self.driver.close()