"""empty message

Revision ID: 1fddf9da2e5e
Revises: ebc8f43d4986
Create Date: 2024-11-22 13:17:45.352178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fddf9da2e5e'
down_revision = 'ebc8f43d4986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_rating', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_dataset_rating', ['user_id', 'dataset_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_rating', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_dataset_rating', type_='unique')

    # ### end Alembic commands ###
