"""Added googleid to user

Revision ID: 43c1089b52dc
Revises: 001
Create Date: 2024-11-07 20:05:00.194412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43c1089b52dc'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=256), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
