"""empty message

Revision ID: 551fa9081b70
Revises: 
Create Date: 2024-11-12 09:32:03.443824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '551fa9081b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['github_id'])

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('is_developer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_developer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('github', mysql.VARCHAR(length=39), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
