"""empty message

Revision ID: 5a20679d5b3f
Revises: 6706d9a1ec66
Create Date: 2024-12-01 18:41:17.700012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a20679d5b3f'
down_revision = '6706d9a1ec66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', sa.Integer(), nullable=False))
        batch_op.drop_index('_user_dataset_uc')
        batch_op.create_unique_constraint('_user_feature_model_uc', ['user_id', 'feature_model_id'])
        batch_op.drop_constraint('fm_rating_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('dataset_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fm_rating_ibfk_1', 'data_set', ['dataset_id'], ['id'])
        batch_op.drop_constraint('_user_feature_model_uc', type_='unique')
        batch_op.create_index('_user_dataset_uc', ['user_id', 'dataset_id'], unique=True)
        batch_op.drop_column('feature_model_id')

    # ### end Alembic commands ###
