"""empty message

Revision ID: 73b017e2dbd7
Revises: a69c50e2afd1
Create Date: 2024-11-10 16:45:12.855999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b017e2dbd7'
down_revision = 'a69c50e2afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github', sa.String(length=39), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('github')

    # ### end Alembic commands ###
