"""empty message

Revision ID: e16c1b038c17
Revises: 89490e30ae31
Create Date: 2024-11-11 19:17:20.252382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e16c1b038c17'
down_revision = '89490e30ae31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcid_id', sa.String(length=19), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(None, ['orcid_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('orcid_id')

    # ### end Alembic commands ###
