"""empty message

Revision ID: f102ec75299f
Revises: 1fddf9da2e5e
Create Date: 2024-11-22 13:20:06.556360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f102ec75299f'
down_revision = '1fddf9da2e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_rating', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
