"""empty message

Revision ID: f74959573e76
Revises: 22cc32aab8bf
Create Date: 2024-12-06 20:00:16.683088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74959573e76'
down_revision = '22cc32aab8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakenodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('dep_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fakenodo')
    # ### end Alembic commands ###
