# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestDevelopergithub:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testdevelopergithub(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(971, 1092)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.XPATH, "/html/body/div/div/nav/a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "a.sidebar-link[href='/profile/edit']"
        ).click()
        self.driver.find_element(By.ID, "github").click()
        self.driver.find_element(By.ID, "github").click()
        element = self.driver.find_element(By.ID, "github")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "github").send_keys("Cargarmar18")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
