# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from core.selenium.common import initialize_driver


class TestSeleniumverdadero2():
    def setup_method(self):
        self.driver = initialize_driver()
        self.vars = {}               
    def teardown_method(self, method): self.driver.quit()   
    def test_seleniumverdadero2(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1850, 1053)
        self.driver.find_element(By.LINK_TEXT, "Explore").click()
        self.driver.find_element(By.ID, "search-query").click()
        self.driver.find_element(By.ID, "search-query").send_keys("Cats")
        self.driver.find_element(By.ID, "search-query").send_keys(Keys.ENTER)
