name: Run Seeders on Render

on:
  workflow_dispatch:

jobs:
  trigger-render-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Job
        run: |
          curl --request POST "${{ secrets.RENDER_SERVICE_URL }}" \
              --header "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
              --header "Content-Type: application/json" \
              --data-raw "{
                  \"startCommand\": \"echo 'y' | rosemary db:seed --reset\"
              }"
